//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace INLANDMARINA.MARINA.App
{


    public partial class Docks
    {

        /// <summary>
        /// LeaseSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INLANDMARINA.MARINA.App.Controls.LeaseSelector LeaseSelector;
    }
}
